#!/bin/bash
# Prevents pushing to main, including force

echo -e "===\n>> Pre-push: Checking branch name..."

BRANCH=`git rev-parse --abbrev-ref HEAD`
PROTECTED_BRANCHES="^main"

if [[ $1 != *"$BRANCH"* ]]
then
  echo -e "\n🚫 You are currently in branch: $BRANCH\nPlease use (git push origin $BRANCH)\n" && exit 1
fi

if [[ "$BRANCH" =~ $PROTECTED_BRANCHES ]]
then
  echo -e "\n🚫 Cannot push to remote branch "$BRANCH", please create your own branch and create a PR." && exit 1
fi

echo -e ">> Finished checking branch name!\n==="

exit 0
