#!/bin/bash

# Protect main from accidental commits.
echo -e "===\n>> Pre-commit: Checking branch name..."
branchName=$(git branch | grep '*' | sed 's/* //')

if [ $branchName == 'main' ]
then
  echo -e "\n🚫 You are not allowed to commit directly to main! Please commit to a new branch then open a PR.\n" && exit 1
fi

echo -e ">> Finished checking branch name!\n==="

exit 0
